repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [
          "--profile",
          "black",
          "--use-parentheses",
          ".",
        ]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
        args: [
          "--line-length",
          "79",
          ".",
        ]
  - repo: https://github.com/PyCQA/flake8/
    rev: 4.0.1
    hooks:
      - id: flake8
        args: [
          ".",
        ]
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        additional_dependencies: [
          "django-stubs",
          "djangorestframework-stubs",
        ]
        args: [
          "--no-implicit-optional",
          "--no-strict-optional",
          "--disallow-untyped-defs",
        ]
