repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/asottile/pyupgrade
    rev: v2.37.0
    hooks:
      - id: pyupgrade
        args: [
          "--py3-plus",
          "--keep-runtime-typing",
        ]
  - repo: https://github.com/myint/autoflake
    rev: v1.4
    hooks:
      - id: autoflake
        args: [
          "--recursive",
          "--in-place",
          "--remove-all-unused-imports",
          "--remove-unused-variables",
          "--expand-star-imports",
          "--exclude",
          "__init__.py",
          "--remove-duplicate-keys",
        ]
  - repo: https://github.com/pycqa/isort
    rev: 5.10.1
    hooks:
      - id: isort
        args: [
          "--profile",
          "black",
          "--use-parentheses",
        ]
  - repo: https://github.com/psf/black
    rev: 22.6.0
    hooks:
      - id: black
  - repo: https://github.com/PyCQA/flake8/
    rev: 4.0.1
    hooks:
      - id: flake8
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.961
    hooks:
      - id: mypy
        additional_dependencies: [
          "django-stubs",
          "djangorestframework-stubs",
        ]
        args: [
          "--no-implicit-optional",
          "--no-strict-optional",
          "--disallow-untyped-defs",
        ]
